'use client';

import { ProductCategoryDto, StatusEnum } from '@data-access/index';
import { useEffect, useState } from 'react';

interface CategoryFormProps {
  isCreateMode: boolean;
  selectedCategory: ProductCategoryDto | null;
  successMessage: string | null;
  onSave: (category: ProductCategoryDto) => void;
  onDelete: () => void;
  onCancel: () => void;
  isAdminUser?: boolean;
}

export default function CategoryForm({
  isCreateMode,
  selectedCategory,
  successMessage,
  onSave,
  onDelete,
  onCancel,
  isAdminUser = false
}: CategoryFormProps) {
  const [userHasMadeSelections, setUserHasMadeSelections] = useState(false);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  
  // Form state for controlled inputs
  const [formData, setFormData] = useState({
    productCategoryName: '',
    changeReason: ''
  });

  // Set initial values when editing (only when user hasn't made selections)
  useEffect(() => {
    if (!isCreateMode && selectedCategory && !userHasMadeSelections) {
      // Initialize form data
      setFormData({
        productCategoryName: selectedCategory.productCategoryName || '',
        changeReason: selectedCategory.changeReason || ''
      });
    }
  }, [isCreateMode, selectedCategory, userHasMadeSelections]);

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const productCategoryName = formData.productCategoryName.trim();
    
    // Validate required fields
    const errors: string[] = [];
    
    if (!productCategoryName) {
      errors.push('Product category name is required.');
    }
    
    // Validate change reason for non-create mode (only required for non-admin users)
    if (!isCreateMode && !isAdminUser && (!formData.changeReason || formData.changeReason.trim() === '')) {
      errors.push('Please provide a reason for the change.');
    }
    
    if (errors.length > 0) {
      setValidationErrors(errors);
      return;
    }
    
    // Clear validation errors if validation passes
    setValidationErrors([]);
    
    if (isCreateMode) {
      const newCategory = {
        productCategoryId: '', // Will be generated by the backend
        productCategoryName: productCategoryName,
        status: StatusEnum.NEW_RECORD // Default status for new categories
      } as ProductCategoryDto;
      onSave(newCategory);
    } else {
      // Determine status based on user role
      const newStatus = isAdminUser ? StatusEnum.ACTIVE : StatusEnum.FOR_APPROVAL;
      
      const updatedCategory = {
        ...selectedCategory,
        productCategoryName: productCategoryName,
        status: newStatus,
        changeReason: formData.changeReason.trim() || undefined
      } as ProductCategoryDto;
      onSave(updatedCategory);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      {/* Success message */}
      {successMessage && (
        <div className="flex items-center gap-3 rounded-xl border-2 border-green-500 bg-green-50 p-4 text-green-700 shadow-sm">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-green-500 text-sm font-bold text-white">
            ✓
          </div>
          <span className="text-sm font-semibold">{successMessage}</span>
        </div>
      )}

      {/* Validation errors */}
      {validationErrors.length > 0 && (
        <div className="space-y-3 rounded-xl border-2 border-red-500 bg-red-50 p-4 shadow-sm">
          <div className="flex items-center gap-2 text-sm font-semibold text-red-700">
            <span className="text-base">⚠️</span>
            <span>Please fix the following errors:</span>
          </div>
          <ul className="list-disc space-y-1 pl-5 text-sm text-red-700">
            {validationErrors.map((error, index) => (
              <li key={index}>{error}</li>
            ))}
          </ul>
        </div>
      )}
      
      {/* Details Container */}
      <div className="space-y-6">
        {/* Basic Information Section */}
        <div className="space-y-4">
          <div className="border-2 border-gray-200 rounded-xl p-4 sm:p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-blue-600 rounded-lg shadow-sm text-white">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                </svg>
              </div>
              <h3 className="text-base font-bold text-blue-600 m-0">
                Category Information
              </h3>
            </div>
            <div className="grid grid-cols-1 gap-6">
              {/* Category Name */}
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-500 rounded-full"></span>
                  Category Name
                </label>
                <input
                  type="text"
                  name="productCategoryName"
                  value={formData.productCategoryName}
                  onChange={(e) => {
                    setFormData(prev => ({ ...prev, productCategoryName: e.target.value }));
                    setUserHasMadeSelections(true);
                  }}
                  placeholder={isCreateMode ? 'Enter category name' : ''}
                  disabled={!isCreateMode && selectedCategory?.status !== StatusEnum.ACTIVE}
                  className={`w-full px-4 py-3 border-2 rounded-xl text-sm font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200 ${
                    !isCreateMode && selectedCategory?.status !== StatusEnum.ACTIVE
                      ? 'border-gray-200 bg-gray-50 text-gray-500 cursor-not-allowed'
                      : 'border-gray-300 bg-white text-gray-700'
                  }`}
                  required
                />
              </div>
            </div>
          </div>
        </div>

        {/* Change Reason and Modification Made Field - Only show for non-create mode and non-admin users */}
        {!isCreateMode && !isAdminUser && (
          <div className="space-y-4">
            <div className="border-2 border-gray-200 rounded-xl p-4 sm:p-6">
              <div className="mb-4 flex items-center gap-3">
                <div className="p-2 bg-blue-600 text-white rounded-lg shadow-sm">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                </div>
                <h3 className="text-base font-bold text-blue-600 m-0">
                  Change Reason
                </h3>
              </div>
              <div className="group">
                <label className="mb-2 flex items-center gap-2 text-sm font-bold text-gray-700">
                  <span className="w-1.5 h-1.5 bg-blue-500 rounded-full"></span>
                  Change Reason and Modification Made
                </label>
                <textarea
                  name="changeReason"
                  value={formData.changeReason}
                  onChange={(e) => {
                    setFormData(prev => ({ ...prev, changeReason: e.target.value }));
                    setUserHasMadeSelections(true);
                  }}
                  placeholder="Please explain the reason for this change..."
                  rows={3}
                  disabled={!isCreateMode && selectedCategory?.status !== StatusEnum.ACTIVE}
                  className={`min-h-[80px] w-full resize-vertical rounded-xl border-2 px-4 py-3 text-sm font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all duration-200 ${
                    !isCreateMode && selectedCategory?.status !== StatusEnum.ACTIVE
                      ? 'border-gray-200 bg-gray-50 text-gray-500 cursor-not-allowed'
                      : 'border-gray-300 bg-white text-gray-700'
                  }`}
                  required={!isAdminUser}
                />
                <div className="text-xs text-gray-500 mt-2">
                  This field is required when making changes to the category record.
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="mt-8 flex flex-col gap-3 border-t-2 border-gray-200 pt-6 sm:flex-row sm:items-center sm:justify-between">
        {!isCreateMode && selectedCategory?.status === StatusEnum.ACTIVE ? (
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              onDelete();
            }}
            className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-6 py-3 font-semibold text-white shadow-sm transition-colors duration-200 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          </button>
        ) : (
          <div className="hidden sm:block" />
        )}

        <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center">
          {(isCreateMode || selectedCategory?.status === StatusEnum.ACTIVE || (selectedCategory && !isAdminUser && selectedCategory.status === StatusEnum.FOR_APPROVAL)) && (
            <button
              type="submit"
              disabled={!isCreateMode && selectedCategory?.status !== StatusEnum.ACTIVE && !isAdminUser}
              className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white shadow-sm transition-colors duration-200 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              {isCreateMode ? 'Create Category' : 'Save Changes'}
            </button>
          )}
          <button
            type="button"
            onClick={onCancel}
            className="flex items-center justify-center gap-2 rounded-xl border-2 border-gray-300 bg-white px-6 py-3 font-semibold text-gray-700 shadow-sm transition-all duration-200 hover:border-gray-400 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
            Cancel
          </button>
        </div>
      </div>
    </form>
  );
}
