'use client';

import { extractErrorMessage, ReturnGoodSoldApi, ReturnGoodSoldDto, useEnv, useLocalStore, useSessionStore } from '@data-access/index';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import ReturnGoodSoldForm from '../[id]/edit/components/ReturnGoodSoldForm';
import RgsCreatedDialog from '../components/RgsCreatedDialog';

export default function CreateReturnGoodSoldPage() {
  const [isLoading, setIsLoading] = useState(false);
  const [createdRgs, setCreatedRgs] = useState<ReturnGoodSoldDto | null>(null);
  const [showSuccessDialog, setShowSuccessDialog] = useState(false);
  const { env } = useEnv();
  const { authedUser } = useLocalStore();
  const { setFlashNotification } = useSessionStore();
  const router = useRouter();
  
  // Check if user is admin or super admin
  const isAdminUser = authedUser?.userRole === 'ADMIN' || authedUser?.userRole === 'SUPER_ADMIN';

  const handleSave = async (record: ReturnGoodSoldDto) => {
    try {
      setIsLoading(true);
      
      // SECURITY: Only get user role if BYPASS_AUTH is enabled AND in development mode
      // This prevents role parameter leakage in production
      const userRole = (env.BYPASS_AUTH === 'ENABLED' && process.env.NODE_ENV === 'development') 
          ? authedUser?.userRole 
          : undefined;
      
      // Create new return good sold record
      // Note: rgsDocno is auto-generated by backend, so we don't include it
      const createdRgsData = await ReturnGoodSoldApi.createReturnGoodSold({
        invoiceId: record.invoiceId,
        customerId: record.customerId,
        customerName: record.customerName,
        areaId: record.areaId,
        areaName: record.areaName,
        areaPrefixId: (record as any).areaPrefixId,
        invoiceDocno: record.invoiceDocno,
        dateReturned: record.dateReturned,
        originalInvoiceDetails: record.originalInvoiceDetails,
        modifiedInvoiceDetails: record.modifiedInvoiceDetails,
        status: record.status,
        activityLogs: record.activityLogs,
        forApprovalVersion: record.forApprovalVersion,
        changeReason: record.changeReason
      } as any, userRole);
      
      // Store the created RGS and show dialog instead of redirecting immediately
      setCreatedRgs(createdRgsData);
      setShowSuccessDialog(true);
      
      setFlashNotification({
        title: 'Success!',
        message: 'Return good sold record created successfully!',
        alertType: 'success'
      });
      
    } catch (error) {
      console.error('Error creating return good sold:', error);
      const errorMessage = extractErrorMessage(error, 'Failed to create return good sold record. Please try again.');
      setFlashNotification({
        title: 'Error',
        message: errorMessage,
        alertType: 'error'
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleCancel = () => {
    router.push('/invoicing/return-good-sold');
  };

  const handleDelete = () => {
    // Not applicable for create mode
  };

  const handleApprove = () => {
    // Not applicable for create mode
  };

  const handleDeny = () => {
    // Not applicable for create mode
  };

  const handleAcknowledge = () => {
    setShowSuccessDialog(false);
    router.replace('/invoicing/return-good-sold');
  };

  return (
    <div className="p-4 sm:p-6 space-y-6">
      <div>
        <nav className="flex items-center gap-2">
          <a href="/dashboard" className="text-blue-500 no-underline text-sm hover:text-blue-600 transition-colors duration-200">
            Home
          </a>
          <span className="text-gray-400">/</span>
          <a href="/invoicing" className="text-blue-500 no-underline text-sm hover:text-blue-600 transition-colors duration-200">
            Invoicing
          </a>
          <span className="text-gray-400">/</span>
          <a href="/invoicing/return-good-sold" className="text-blue-500 no-underline text-sm hover:text-blue-600 transition-colors duration-200">
            Return Good Sold
          </a>
          <span className="text-gray-400">/</span>
          <span className="text-gray-800 text-sm font-medium">Create</span>
        </nav>
      </div>

      <div className="flex justify-center">
        <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-xl w-full sm:max-w-4xl">
          {/* Tab Navigation - Only Details tab for create mode */}
          <div className="bg-gray-50 border-b-2 border-blue-200 rounded-t-xl p-2 overflow-x-auto">
            <div className="flex gap-2 flex-nowrap">
              <button
                className="flex-shrink-0 px-5 py-3 rounded-lg font-semibold text-sm bg-blue-600 text-white shadow-sm"
                disabled
              >
                <span className="flex items-center gap-2">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Return Good Sold Information
                </span>
              </button>
            </div>
          </div>
          
          {/* Tab Content */}
          <div className="bg-white p-4 sm:p-6">
            <ReturnGoodSoldForm
              isCreateMode={true}
              selectedRecord={null}
              successMessage={null}
              isAdminUser={isAdminUser}
              isLoading={isLoading}
              activeTab="details"
              onTabChange={() => {}} // Not used in create mode
              onSave={handleSave}
              onDelete={handleDelete}
              onApprove={handleApprove}
              onDeny={handleDeny}
              onCancel={handleCancel}
            />
          </div>
        </div>
      </div>

      {/* Success Dialog */}
      <RgsCreatedDialog
        show={showSuccessDialog}
        rgs={createdRgs}
        onAcknowledge={handleAcknowledge}
      />
    </div>
  );
}

