export enum StatusEnum {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    FOR_APPROVAL = 'FOR_APPROVAL',
    FOR_DELETION = 'FOR_DELETION',
    FOR_DEACTIVATION = 'FOR_DEACTIVATION',
    NEW_RECORD = 'NEW_RECORD',
    DRAFT = 'DRAFT',
}
