import { Entity } from 'dynamodb-onetable';

export const CustomerSchema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'PK', sort: 'SK' },
        GSI1: { hash: 'GSI1PK', sort: 'GSI1SK' },
        GSI2: { hash: 'GSI2PK', sort: 'GSI2SK' },
        GSI3: { hash: 'GSI3PK', sort: 'GSI3SK' },
        GSI4: { hash: 'GSI4PK', sort: 'GSI4SK' },
        GSI5: { hash: 'GSI5PK', sort: 'GSI5SK' },
        GSI6: { hash: 'GSI6PK', sort: 'GSI6SK' },
    },
    models: {
        Customer: {
            PK: { type: String, value: 'CUSTOMER', hidden: false },
            SK: { type: String, value: '${customerId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            customerId: { type: String, generate: 'ulid' },
            customerName: { type: String, required: false },
            email: { type: String, required: false },
            address1: { type: String, required: false },
            address2: { type: String, required: false },
            balance: { type: Number, required: false },
            contactNo: { type: String, required: false },
            contactPerson: { type: String, required: false },
            townId: { type: String, required: false },
            townName: { type: String, required: false },
            creditLimit: { type: Number, required: false },
            customerCreditLimit: { type: Number, required: false },
            tinNumber: { type: String, required: false },
            areaId: { type: String, required: false },
            areaName: { type: String, required: false },
            customerClassificationId: { type: String, required: false },
            customerClassificationName: { type: String, required: false },
            customerTypeId: { type: String, required: false },
            customerTypeName: { type: String, required: false },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            activityLogs: { type: Array },
            customerTerms: { type: Array },
            customerDeals: { type: Array },
            GSI1PK: { type: String, value: 'CUSTOMER', hidden: false },
            GSI1SK: { type: String, value: '${customerName}', hidden: false },
            GSI2PK: { type: String, value: 'CUSTOMER#${status}', hidden: false },
            GSI2SK: { type: String, value: '${customerName}', hidden: false },
            GSI3PK: { type: String, value: 'CUSTOMER#${customerClassificationId}', hidden: false },
            GSI3SK: { type: String, value: '${customerName}', hidden: false },
            GSI4PK: { type: String, value: 'CUSTOMER#${customerTypeId}', hidden: false },
            GSI4SK: { type: String, value: '${customerName}', hidden: false },
            GSI5PK: { type: String, value: 'CUSTOMER#${areaId}', hidden: false },
            GSI5SK: { type: String, value: '${customerName}', hidden: false },
            GSI6PK: { type: String, value: 'CUSTOMER#${townId}', hidden: false },
            GSI6SK: { type: String, value: '${customerName}', hidden: false },
        },
        CustomerClassification: {
            PK: { type: String, value: 'CUSTOMER_CLASSIFICATION', hidden: false },
            SK: { type: String, value: '${customerClassificationId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            activityLogs: { type: Array },
            customerClassificationId: { type: String, generate: 'ulid' },
            customerClassificationName: { type: String },
            forApprovalVersion: { type: Object },
            GSI1PK: { type: String, value: 'CUSTOMER_CLASSIFICATION', hidden: false },
            GSI1SK: { type: String, value: '${customerClassificationName}', hidden: false },
            GSI2PK: { type: String, value: 'CUSTOMER_CLASSIFICATION#${status}', hidden: false },
            GSI2SK: { type: String, value: '${customerClassificationName}', hidden: false },
        },
        CustomerType: {
            PK: { type: String, value: 'CUSTOMER_TYPE', hidden: false },
            SK: { type: String, value: '${customerTypeId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            customerTypeId: { type: String, generate: 'ulid' },
            customerTypeName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            GSI1PK: { type: String, value: 'CUSTOMER_TYPE', hidden: false },
            GSI1SK: { type: String, value: '${customerTypeName}', hidden: false },
            GSI2PK: { type: String, value: 'CUSTOMER_TYPE#${status}', hidden: false },
            GSI2SK: { type: String, value: '${customerTypeName}', hidden: false },
        },
        Terms: {
            PK: { type: String, value: 'TERMS', hidden: false },
            SK: { type: String, value: '${termsId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            termsId: { type: String, generate: 'ulid' },
            termsName: { type: String },
            days: { type: Number },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            GSI1PK: { type: String, value: 'TERMS', hidden: false },
            GSI1SK: { type: String, value: '${termsName}', hidden: false },
            GSI2PK: { type: String, value: 'TERMS#${status}', hidden: false },
            GSI2SK: { type: String, value: '${termsName}', hidden: false },
        },
        Area: {
            PK: { type: String, value: 'AREA', hidden: false },
            SK: { type: String, value: '${areaId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            areaId: { type: String, generate: 'ulid' },
            areaName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            GSI1PK: { type: String, value: 'AREA', hidden: false },
            GSI1SK: { type: String, value: '${areaName}', hidden: false },
            GSI2PK: { type: String, value: 'AREA#${status}', hidden: false },
            GSI2SK: { type: String, value: '${areaName}', hidden: false },
        },
        Town: {
            PK: { type: String, value: 'TOWN', hidden: false },
            SK: { type: String, value: '${townId}', hidden: false },
            townId: { type: String, generate: 'ulid' },
            areaId: { type: String, required: false },
            townName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD'],
                required: false,
            },
            GSI1PK: { type: String, value: 'TOWN', hidden: false },
            GSI1SK: { type: String, value: '${townName}', hidden: false },
            GSI2PK: { type: String, value: 'TOWN#${status}', hidden: false },
            GSI2SK: { type: String, value: '${townName}', hidden: false },
            GSI3PK: { type: String, value: 'TOWN#${areaId}#${status}', hidden: false },
            GSI3SK: { type: String, value: '${townName}', hidden: false },
        },
    } as const,
    params: {
        isoDates: true,
        timestamps: true,
    },
};

export type CustomerDataType = Entity<typeof CustomerSchema.models.Customer>;
export type CustomerClassificationDataType = Entity<typeof CustomerSchema.models.CustomerClassification>;
export type CustomerTypeDataType = Entity<typeof CustomerSchema.models.CustomerType>;
export type TermsDataType = Entity<typeof CustomerSchema.models.Terms>;
export type AreaDataType = Entity<typeof CustomerSchema.models.Area>;
export type TownDataType = Entity<typeof CustomerSchema.models.Town>;
