import { Entity } from 'dynamodb-onetable';

export const InventorySchema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'PK', sort: 'SK' },
        GSI1: { hash: 'GSI1PK', sort: 'GSI1SK' },
        GSI2: { hash: 'GSI2PK', sort: 'GSI2SK' },
        GSI3: { hash: 'GSI3PK', sort: 'GSI3SK' },
        GSI4: { hash: 'GSI4PK', sort: 'GSI4SK' },
        GSI5: { hash: 'GSI5PK', sort: 'GSI5SK' },
        GSI6: { hash: 'GSI6PK', sort: 'GSI6SK' },
    },
    models: {
        Stock: {
            PK: { type: String, value: 'STOCK', hidden: false },
            SK: { type: String, value: '${stockId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            stockId: { type: String, generate: 'ulid' },
            lotNo: { type: String, required: false },
            productId: { type: String, required: false },
            productName: { type: String, required: false },
            quantityOnHand: { type: Number, required: false }, //actual quantity on hand not considering invoice in draft mode and not considering inventory transfer in transit
            availableQuantity: { type: Number, required: false }, // actual quantity on hand considering invoice in draft mode , to handle invoice records being created at the same time
            productUnitId: { type: String, required: false },
            productUnitName: { type: String, required: false },
            expirationDate: { type: String, required: false },
            stockTypeId: { type: String, required: false },
            stockTypeName: { type: String, required: false },
            forApprovalVersion: { type: Object },
            approverMessage: { type: String, required: false },
            activityLogs: { type: Array },
            changeReason: { type: String, required: false },
            GSI1PK: { type: String, value: 'STOCK', hidden: false },
            GSI1SK: { type: String, value: '${productName}', hidden: false },
            GSI2PK: { type: String, value: 'STOCK#${status}', hidden: false },
            GSI2SK: { type: String, value: '${productName}', hidden: false },
            GSI3PK: { type: String, value: 'STOCK#${status}', hidden: false },
            GSI3SK: { type: String, value: '${productId}', hidden: false },
            GSI4PK: { type: String, value: 'STOCK#${status}#${productUnitId}#${productId}', hidden: false },
            GSI4SK: { type: String, value: '${lotNo}', hidden: false },
            GSI5PK: { type: String, value: 'STOCK#${status}#${productUnitId}#${productId}', hidden: false },
            GSI5SK: { type: String, value: '${expirationDate}', hidden: false },
        },
        StockType: {
            PK: { type: String, value: 'STOCK_TYPE', hidden: false },
            SK: { type: String, value: '${stockTypeId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            stockTypeId: { type: String, generate: 'ulid' },
            stockTypeName: { type: String, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'STOCK_TYPE', hidden: false },
            GSI1SK: { type: String, value: '${stockTypeName}', hidden: false },
            GSI2PK: { type: String, value: 'STOCK_TYPE#${status}', hidden: false },
            GSI2SK: { type: String, value: '${stockTypeName}', hidden: false },
        },
        RawMaterials: {
            PK: { type: String, value: 'RAW_MATERIAL', hidden: false },
            SK: { type: String, value: '${rawMaterialId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            rawMaterialId: { type: String, generate: 'ulid' },
            rawMaterialName: { type: String },
            description: { type: String, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIAL', hidden: false },
            GSI1SK: { type: String, value: '${rawMaterialName}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIAL#${status}', hidden: false },
            GSI2SK: { type: String, value: '${rawMaterialName}', hidden: false },
        },
        RawMaterialSupplier: {
            PK: { type: String, value: 'RAW_MATERIAL_SUPPLIER', hidden: false },
            SK: { type: String, value: '${rawMaterialSupplierId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            rawMaterialSupplierId: { type: String, generate: 'ulid' },
            rawMaterialSupplierName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIAL_SUPPLIER', hidden: false },
            GSI1SK: { type: String, value: '${rawMaterialSupplierName}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIAL_SUPPLIER#${status}', hidden: false },
            GSI2SK: { type: String, value: '${rawMaterialSupplierName}', hidden: false },
        },
        RawMaterialsLocation: {
            PK: { type: String, value: 'RAW_MATERIAL_LOCATION', hidden: false },
            SK: { type: String, value: '${rawMaterialsLocationId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            rawMaterialsLocationId: { type: String, generate: 'ulid' },
            rawMaterialsLocationName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIAL_LOCATION', hidden: false },
            GSI1SK: { type: String, value: '${rawMaterialsLocationName}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIAL_LOCATION#${status}', hidden: false },
            GSI2SK: { type: String, value: '${rawMaterialsLocationName}', hidden: false },
        },
        RawMaterialsStock: {
            PK: { type: String, value: 'RAW_MATERIAL_STOCK', hidden: false },
            SK: { type: String, value: '${rawMaterialsStockId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            rawMaterialsStockId: { type: String, generate: 'ulid' },
            rawMaterialId: { type: String, required: false },
            rawMaterialName: { type: String, required: false },
            rawMaterialUnitId: { type: String, required: false },
            rawMaterialUnitName: { type: String, required: false },
            rawMaterialSupplierId: { type: String, required: false },
            rawMaterialSupplierName: { type: String, required: false },
            rawMaterialsLocationId: { type: String, required: false },
            rawMaterialsLocationName: { type: String, required: false },
            rawMaterialNamePoNo: { type: String, required: false },
            qty: { type: Number, required: false },
            lotNo: { type: String, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIAL_STOCK', hidden: false },
            GSI1SK: { type: String, value: '${rawMaterialName}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIAL_STOCK#${status}', hidden: false },
            GSI2SK: { type: String, value: '${rawMaterialName}', hidden: false },
        },
        RawMaterialsPurchaseOrder: {
            PK: { type: String, value: 'RAW_MATERIALS_PURCHASE_ORDER', hidden: false },
            SK: { type: String, value: '${rawMaterialsPurchaseOrderId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            poStatus: {
                type: String,
                enum: ['SYSTEM_GENERATED', 'PENDING', 'PARTIAL', 'COMPLETED'],
                required: false,
            },
            rawMaterialsPurchaseOrderId: { type: String, generate: 'ulid' },
            rawMaterialSupplierId: { type: String, required: false },
            rawMaterialSupplierName: { type: String, required: false },
            poDate: { type: String, required: false },
            docNo: { type: String, required: false },
            purchaseOrderDetails: { type: Array, required: false },
            deliveredPurchaseOrderDetails: { type: Array, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIALS_PURCHASE_ORDER', hidden: false },
            GSI1SK: { type: String, value: '${poDate}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIALS_PURCHASE_ORDER#${status}', hidden: false },
            GSI2SK: { type: String, value: '${poDate}', hidden: false },
            GSI3PK: { type: String, value: 'RAW_MATERIALS_PURCHASE_ORDER#PO_STATUS#${poStatus}', hidden: false },
            GSI3SK: { type: String, value: '${poDate}', hidden: false },
            GSI4PK: {
                type: String,
                value: 'RAW_MATERIALS_PURCHASE_ORDER#SUPPLIER#${rawMaterialSupplierId}',
                hidden: false,
            },
            GSI4SK: { type: String, value: '${poDate}', hidden: false },
            GSI5PK: { type: String, value: 'RAW_MATERIALS_PURCHASE_ORDER', hidden: false },
            GSI5SK: { type: String, value: '${docNo}', hidden: false },
        },
        RawMaterialUnits: {
            PK: { type: String, value: 'RAW_MATERIAL_UNIT', hidden: false },
            SK: { type: String, value: '${rawMaterialUnitId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            rawMaterialUnitId: { type: String, generate: 'ulid' },
            rawMaterialUnitName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'RAW_MATERIAL_UNIT', hidden: false },
            GSI1SK: { type: String, value: '${rawMaterialUnitName}', hidden: false },
            GSI2PK: { type: String, value: 'RAW_MATERIAL_UNIT#${status}', hidden: false },
            GSI2SK: { type: String, value: '${rawMaterialUnitName}', hidden: false },
        },
        Supplier: {
            PK: { type: String, value: 'SUPPLIER', hidden: false },
            SK: { type: String, value: '${supplierId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            supplierId: { type: String, generate: 'ulid' },
            supplierName: { type: String, required: false },
            supplierAddress: { type: String, required: false },
            supplierPhone: { type: String, required: false },
            supplierEmail: { type: String, required: false },
            supplierContactPerson: { type: String, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            GSI1PK: { type: String, value: 'SUPPLIER', hidden: false },
            GSI1SK: { type: String, value: '${supplierName}', hidden: false },
            GSI2PK: { type: String, value: 'SUPPLIER#${status}', hidden: false },
            GSI2SK: { type: String, value: '${supplierName}', hidden: false },
        },
        StockDelivery: {
            PK: { type: String, value: 'STOCK_DELIVERY', hidden: false },
            SK: { type: String, value: '${stockDeliveryId}', hidden: false },
            stockDeliveryId: { type: String, generate: 'ulid' },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            forApprovalVersion: { type: Object },
            changeReason: { type: String, required: false },
            approverMessage: { type: String, required: false },
            activityLogs: { type: Array },
            deliveryDetails: { type: Array },
            supplierId: { type: String, required: false },
            supplierName: { type: String, required: false },
            dateReceived: { type: String, required: false },
            docno: { type: String, required: false },
            GSI1PK: { type: String, value: 'STOCK_DELIVERY', hidden: false },
            GSI1SK: { type: String, value: '${docno}', hidden: false },
            GSI2PK: { type: String, value: 'STOCK_DELIVERY#${status}', hidden: false },
            GSI2SK: { type: String, value: '${docno}', hidden: false },
            GSI3PK: { type: String, value: 'STOCK_DELIVERY#${supplierId}', hidden: false },
            GSI3SK: { type: String, value: '${dateReceived}', hidden: false },
            GSI4PK: { type: String, value: 'STOCK_DELIVERY', hidden: false },
            GSI4SK: { type: String, value: '${dateReceived}', hidden: false },
        },
    } as const,
    params: {
        isoDates: true,
        timestamps: true,
    },
};

export type StockDataType = Entity<typeof InventorySchema.models.Stock>;
export type StockTypeDataType = Entity<typeof InventorySchema.models.StockType>;
export type RawMaterialSupplierDataType = Entity<typeof InventorySchema.models.RawMaterialSupplier>;
export type RawMaterialsLocationDataType = Entity<typeof InventorySchema.models.RawMaterialsLocation>;
export type RawMaterialsStockDataType = Entity<typeof InventorySchema.models.RawMaterialsStock>;
export type RawMaterialsPurchaseOrderDataType = Entity<typeof InventorySchema.models.RawMaterialsPurchaseOrder>;
export type RawMaterialsDataType = Entity<typeof InventorySchema.models.RawMaterials>;
export type RawMaterialUnitsDataType = Entity<typeof InventorySchema.models.RawMaterialUnits>;
export type SupplierDataType = Entity<typeof InventorySchema.models.Supplier>;
export type StockDeliveryDataType = Entity<typeof InventorySchema.models.StockDelivery>;
