import { Entity } from 'dynamodb-onetable';

export const InvoicingSchema = {
    version: '0.0.1',
    indexes: {
        primary: { hash: 'PK', sort: 'SK' },
        GSI1: { hash: 'GSI1PK', sort: 'GSI1SK' },
        GSI2: { hash: 'GSI2PK', sort: 'GSI2SK' },
        GSI3: { hash: 'GSI3PK', sort: 'GSI3SK' },
        GSI4: { hash: 'GSI4PK', sort: 'GSI4SK' },
        GSI5: { hash: 'GSI5PK', sort: 'GSI5SK' },
        GSI6: { hash: 'GSI6PK', sort: 'GSI6SK' },
        GSI7: { hash: 'GSI7PK', sort: 'GSI7SK' },
        GSI8: { hash: 'GSI8PK', sort: 'GSI8SK' },
        GSI9: { hash: 'GSI9PK', sort: 'GSI9SK' },
        GSI10: { hash: 'GSI10PK', sort: 'GSI10SK' },
        GSI11: { hash: 'GSI11PK', sort: 'GSI11SK' },
        GSI12: { hash: 'GSI12PK', sort: 'GSI12SK' },
    },
    models: {
        Invoice: {
            PK: { type: String, value: 'INVOICE', hidden: false },
            SK: { type: String, value: '${invoiceId}', hidden: false },
            invoiceId: { type: String, generate: 'ulid' },
            docno: { type: String },
            invoiceDate: { type: String },
            customerId: { type: String },
            customerName: { type: String },
            areaId: { type: String },
            areaName: { type: String },
            territoryManagerId: { type: String },
            territoryManagerName: { type: String },
            salesTypeId: { type: String },
            salesTypeName: { type: String },
            finalAmount: { type: Number },
            invoiceAmount: { type: Number },
            taxAmount: { type: Number },
            contractId: { type: String },
            contractName: { type: String },
            termsId: { type: String },
            termsName: { type: String },
            productPriceTypeId: { type: String },
            productPriceTypeName: { type: String },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT', 'DRAFT'],
                required: false,
            },
            printStatus: { type: String, enum: ['PENDING', 'COMPLETED', 'FOR_REPRINT'], required: false },
            paymentStatus: { type: String, enum: ['PENDING', 'PARTIAL', 'PAID'], required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            invoiceDetails: { type: Array },
            GSI1PK: { type: String, value: 'INVOICE', hidden: false },
            GSI1SK: { type: String, value: '${invoiceId}', hidden: false },
            GSI2PK: { type: String, value: 'INVOICE#${status}', hidden: false },
            GSI2SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI3PK: { type: String, value: 'INVOICE#${customerId}', hidden: false },
            GSI3SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI4PK: { type: String, value: 'INVOICE#${salesTypeId}', hidden: false },
            GSI4SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI5PK: { type: String, value: 'INVOICE#${contractId}', hidden: false },
            GSI5SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI6PK: { type: String, value: 'INVOICE#${termsId}', hidden: false },
            GSI6SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI7PK: { type: String, value: 'INVOICE#${productPriceTypeId}', hidden: false },
            GSI7SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI8PK: { type: String, value: 'INVOICE#${areaId}', hidden: false },
            GSI8SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI9PK: { type: String, value: 'INVOICE#${territoryManagerId}', hidden: false },
            GSI9SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI10PK: { type: String, value: 'INVOICE#${paymentStatus}', hidden: false },
            GSI10SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI11PK: { type: String, value: 'INVOICE', hidden: false },
            GSI11SK: { type: String, value: '${invoiceDate}', hidden: false },
            GSI12PK: { type: String, value: 'INVOICE', hidden: false },
            GSI12SK: { type: String, value: '${docno}', hidden: false },
        },
        SalesType: {
            PK: { type: String, value: 'SALES_TYPE', hidden: false },
            SK: { type: String, value: '${salesTypeId}', hidden: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            salesTypeId: { type: String, generate: 'ulid' },
            salesTypeName: { type: String },
            allowDiscount: { type: Boolean, required: false },
            contractSales: { type: Boolean, required: false },
            defaultDiscount: { type: Number, required: false, default: 0 },
            defaultTax: { type: Number, required: false, default: 0 },
            incomeGenerating: { type: Boolean, required: false },
            taxable: { type: Boolean, required: false },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            GSI1PK: { type: String, value: 'SALES_TYPE', hidden: false },
            GSI1SK: { type: String, value: '${salesTypeName}', hidden: false },
            GSI2PK: { type: String, value: 'SALES_TYPE#${status}', hidden: false },
            GSI2SK: { type: String, value: '${salesTypeName}', hidden: false },
        },
        TerritoryManager: {
            PK: { type: String, value: 'TERRITORY_MANAGER', hidden: false },
            SK: { type: String, value: '${territoryManagerId}', hidden: false },
            territoryManagerId: { type: String, generate: 'ulid' },
            territoryManagerName: { type: String },
            activityLogs: { type: Array },
            forApprovalVersion: { type: Object },
            contactNo: { type: String, required: false },
            status: {
                type: String,
                enum: ['ACTIVE', 'FOR_APPROVAL', 'FOR_DELETION', 'NEW_RECORD', 'DRAFT'],
                required: false,
            },
            GSI1PK: { type: String, value: 'TERRITORY_MANAGER', hidden: false },
            GSI1SK: { type: String, value: '${territoryManagerName}', hidden: false },
            GSI2PK: { type: String, value: 'TERRITORY_MANAGER#${status}', hidden: false },
            GSI2SK: { type: String, value: '${territoryManagerName}', hidden: false },
        },
    } as const,
    params: {
        isoDates: true,
        timestamps: true,
    },
};

export type SalesTypeDataType = Entity<typeof InvoicingSchema.models.SalesType>;
export type TerritoryManagerDataType = Entity<typeof InvoicingSchema.models.TerritoryManager>;
export type InvoiceDataType = Entity<typeof InvoicingSchema.models.Invoice>;
