export enum CustomerBalanceEventEnum {
    INVOICE_CREATED = 'INVOICE_CREATED',
    INVOICE_DELETED = 'INVOICE_DELETED',
    PAYMENT_CREATED = 'PAYMENT_CREATED',
    PAYMENT_DELETED = 'PAYMENT_DELETED',
    OVERPAYMENT_CREDIT = 'OVERPAYMENT_CREDIT',
}
