export enum InvoicePaymentEventEnum {
    PAYMENT_ADDED = 'PAYMENT_ADDED',
    PAYMENT_DELETED = 'PAYMENT_DELETED',
    PAYMENT_UPDATED = 'PAYMENT_UPDATED',
    INVOICE_AMOUNT_CHANGED = 'INVOICE_AMOUNT_CHANGED',
    CUSTOMER_BALANCE_UPDATE = 'CUSTOMER_BALANCE_UPDATE',
    INVOICE_DELETED = 'INVOICE_DELETED',
    INVOICE_UPDATED = 'INVOICE_UPDATED',
    INVOICE_CREATED = 'INVOICE_CREATED',
}
