export enum InvoicePaymentEventEnum {
    PAYMENT_ADDED = 'PAYMENT_ADDED',
    PAYMENT_DELETED = 'PAYMENT_DELETED',
    PAYMENT_UPDATED = 'PAYMENT_UPDATED',
    INVOICE_AMOUNT_CHANGED = 'INVOICE_AMOUNT_CHANGED',
}
