'use client';

import { AreaDto, StatusEnum, TownDto } from '@data-access/index';
import { useEffect, useState } from 'react';
import AreaSearchableSelectionModal from '../../../search-modals/AreaSearchableSelectionModal';
import SelectionField from '../../customer/components/SelectionField';

// Extended TownDto interface to include areaName
interface ExtendedTownDto extends TownDto {
  areaName?: string;
}

interface TownFormProps {
  isCreateMode: boolean;
  selectedTown: TownDto | null;
  successMessage: string | null;
  onSave: (town: TownDto) => void;
  onDelete: () => void;
  onCancel: () => void;
  isAdminUser?: boolean;
}

export default function TownForm({
  isCreateMode,
  selectedTown,
  successMessage,
  onSave,
  onDelete,
  onCancel,
  isAdminUser = false
}: TownFormProps) {
  const [selectedArea, setSelectedArea] = useState<{id: string, name: string} | null>(null);
  const [showAreaModal, setShowAreaModal] = useState(false);
  const [userHasMadeSelections, setUserHasMadeSelections] = useState(false);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  
  // Form state for controlled inputs
  const [formData, setFormData] = useState({
    townName: '',
    changeReason: ''
  });

  // Set initial values when editing (only when user hasn't made selections)
  useEffect(() => {
    if (!isCreateMode && selectedTown && !userHasMadeSelections) {
      if (selectedTown.areaId && selectedTown.areaName) {
        setSelectedArea({
          id: selectedTown.areaId,
          name: selectedTown.areaName
        });
      }
      // Initialize form data
      setFormData({
        townName: selectedTown.townName || '',
        changeReason: selectedTown.changeReason || ''
      });
    }
  }, [isCreateMode, selectedTown, userHasMadeSelections]);
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const townName = formData.townName;
    
    // Validate required fields
    const errors: string[] = [];
    
    if (!selectedArea) {
      errors.push('Please select an area.');
    }
    
    // Validate change reason for non-create mode (only required for non-admin users)
    if (!isCreateMode && !isAdminUser && (!formData.changeReason || formData.changeReason.trim() === '')) {
      errors.push('Please provide a reason for the change.');
    }
    
    if (errors.length > 0) {
      setValidationErrors(errors);
      return;
    }
    
    // Clear validation errors if validation passes
    setValidationErrors([]);
    
    if (isCreateMode) {
      const newTown = {
        townId: '', // Will be generated by the backend
        townName: townName,
        areaId: selectedArea?.id || '',
        areaName: selectedArea?.name || '',
        status: StatusEnum.NEW_RECORD // Default status for new towns
      } as TownDto;
      onSave(newTown);
    } else {
      const updatedTown = {
        ...selectedTown,
        townName: townName,
        areaId: selectedArea?.id || '',
        areaName: selectedArea?.name || '',
        status: StatusEnum.ACTIVE,
        changeReason: formData.changeReason || ''
      } as TownDto;
      onSave(updatedTown);
    }
  };

  const handleAreaSelect = (area: AreaDto) => {
    setSelectedArea({ id: area.areaId, name: area.areaName });
    setUserHasMadeSelections(true);
  };

  const handleClearArea = () => {
    setSelectedArea(null);
  };

  // Status badge helper function with enhanced styling and readable text
  const getStatusBadge = (status: StatusEnum) => {
    // Convert status enum to readable text
    const getStatusText = (s: StatusEnum): string => {
      switch (s) {
        case StatusEnum.ACTIVE:
          return 'Active';
        case StatusEnum.FOR_APPROVAL:
          return 'For Approval';
        case StatusEnum.FOR_DELETION:
          return 'For Deletion';
        case StatusEnum.NEW_RECORD:
          return 'New Record';
        default:
          return s;
      }
    };

    const statusText = getStatusText(status);
    
    // Enhanced styling with shadows and better colors
    let badgeClasses = "";
    let dotColor = "";
    let bgColor = "";
    let textColor = "";
    
    if (status === StatusEnum.ACTIVE) {
      badgeClasses = "bg-gradient-to-r from-green-400 to-emerald-500 text-white shadow-lg shadow-green-500/50";
      dotColor = "bg-white";
      bgColor = "#10b981";
      textColor = "#ffffff";
    } else if (status === StatusEnum.FOR_APPROVAL) {
      badgeClasses = "bg-gradient-to-r from-yellow-400 to-amber-500 text-white shadow-lg shadow-yellow-500/50";
      dotColor = "bg-white";
      bgColor = "#f59e0b";
      textColor = "#ffffff";
    } else if (status === StatusEnum.FOR_DELETION) {
      badgeClasses = "bg-gradient-to-r from-red-400 to-rose-500 text-white shadow-lg shadow-red-500/50";
      dotColor = "bg-white";
      bgColor = "#ef4444";
      textColor = "#ffffff";
    } else if (status === StatusEnum.NEW_RECORD) {
      badgeClasses = "bg-gradient-to-r from-blue-400 to-indigo-500 text-white shadow-lg shadow-blue-500/50";
      dotColor = "bg-white";
      bgColor = "#3b82f6";
      textColor = "#ffffff";
    } else {
      badgeClasses = "bg-gradient-to-r from-gray-400 to-gray-500 text-white shadow-lg shadow-gray-500/50";
      dotColor = "bg-white";
      bgColor = "#6b7280";
      textColor = "#ffffff";
    }
    
    return (
      <span className={`inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-bold ${badgeClasses}`} style={{ backgroundColor: bgColor, color: textColor }}>
        <span className={`w-2 h-2 rounded-full ${dotColor}`}></span>
        {statusText}
      </span>
    );
  };

  return (
    <>
    <form onSubmit={handleSubmit}>
      {/* Success message */}
      {successMessage && (
        <div style={{
          backgroundColor: '#dcfce7',
          border: '2px solid #16a34a',
          borderRadius: '8px',
          padding: '16px',
          marginBottom: '16px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
          animation: 'pulse 2s infinite'
        }}>
          <div style={{
            width: '24px',
            height: '24px',
            backgroundColor: '#16a34a',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'white',
            fontSize: '14px',
            fontWeight: 'bold'
          }}>
            ✓
          </div>
          <span style={{
            color: '#166534',
            fontSize: '14px',
            fontWeight: '600'
          }}>
            {successMessage}
          </span>
        </div>
      )}

      {/* Validation errors */}
      {validationErrors.length > 0 && (
        <div style={{
          backgroundColor: '#fef2f2',
          border: '2px solid #dc2626',
          borderRadius: '8px',
          padding: '16px',
          marginBottom: '16px',
          boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        }}>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
            marginBottom: '8px'
          }}>
            <span style={{ fontSize: '20px' }}>⚠️</span>
            <span style={{ color: '#dc2626', fontWeight: '600' }}>
              Please fix the following errors:
            </span>
          </div>
          <ul style={{
            margin: 0,
            paddingLeft: '20px',
            color: '#dc2626'
          }}>
            {validationErrors.map((error, index) => (
              <li key={index} style={{ marginBottom: '4px' }}>
                {error}
              </li>
            ))}
          </ul>
        </div>
      )}
      
      {/* Status Display for Edit Mode - Prominently displayed at top */}
      {!isCreateMode && selectedTown && (
        <div className="bg-gradient-to-br from-white to-gray-50 border-2 border-gray-200 rounded-xl p-4 shadow-md mb-6">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-br from-rose-500 to-pink-600 rounded-lg shadow-md">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div className="flex items-center">
              {getStatusBadge(selectedTown.status || StatusEnum.ACTIVE)}
            </div>
          </div>
        </div>
      )}
      
      {/* Details Container */}
      <div className="space-y-6">
        {/* Basic Information Section */}
        <div className="space-y-4">
          <div className="border-2 border-gray-200 rounded-xl p-4">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg shadow-md">
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                </svg>
              </div>
              <h3 className="text-base font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                Town Information
              </h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Town Name */}
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-500 rounded-full"></span>
                  Town Name
                </label>
                <input
                  type="text"
                  name="townName"
                  value={formData.townName}
                  onChange={(e) => setFormData(prev => ({ ...prev, townName: e.target.value }))}
                  placeholder={isCreateMode ? 'Enter town name' : ''}
                  disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
                  className={`w-full px-4 py-3 border-2 rounded-xl text-sm font-medium shadow-sm transition-all duration-200 ${
                    !isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE
                      ? 'border-gray-200 bg-gradient-to-br from-gray-50 to-white text-gray-500 cursor-not-allowed'
                      : 'border-gray-200 bg-gradient-to-br from-gray-50 to-white text-gray-700 group-hover:border-blue-300 group-hover:shadow-md'
                  }`}
                  required
                />
              </div>

              {/* Area */}
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></span>
                  Area *
                </label>
                <SelectionField
                  label=""
                  selectedItem={selectedArea}
                  onSelect={() => setShowAreaModal(true)}
                  onClear={handleClearArea}
                  buttonText="Select Area"
                  disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Change Reason and Modification Made Field - Only show for non-create mode and non-admin users */}
        {!isCreateMode && !isAdminUser && (
          <div className="space-y-4">
            <div className="border-2 border-gray-200 rounded-xl p-4">
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-gradient-to-br from-amber-500 to-yellow-600 rounded-lg shadow-md">
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                </div>
                <h3 className="text-base font-bold bg-gradient-to-r from-amber-600 to-yellow-600 bg-clip-text text-transparent">
                  Change Reason
                </h3>
              </div>
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full"></span>
                  Change Reason and Modification Made
                </label>
                <textarea
                  name="changeReason"
                  value={formData.changeReason}
                  onChange={(e) => setFormData(prev => ({ ...prev, changeReason: e.target.value }))}
                  placeholder="Please explain the reason for this change..."
                  rows={3}
                  disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
                  className={`w-full px-4 py-3 border-2 rounded-xl text-sm font-medium shadow-sm transition-all duration-200 resize-vertical min-h-[80px] ${
                    !isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE
                      ? 'border-gray-200 bg-gradient-to-br from-gray-50 to-white text-gray-500 cursor-not-allowed'
                      : 'border-gray-200 bg-gradient-to-br from-gray-50 to-white text-gray-700 group-hover:border-amber-300 group-hover:shadow-md'
                  }`}
                  required={!isAdminUser}
                />
                <div className="text-xs text-gray-500 mt-2">
                  This field is required when making changes to the town record.
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="flex justify-between items-center mt-8 pt-6 border-t-2 border-gradient-to-r from-gray-200 to-gray-100">
        {!isCreateMode && selectedTown?.status === StatusEnum.ACTIVE ? (
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              onDelete();
            }}
            className="px-6 py-3 bg-gradient-to-r from-red-500 to-red-600 text-white font-semibold rounded-xl shadow-lg shadow-red-500/30 hover:shadow-xl hover:shadow-red-500/40 hover:from-red-600 hover:to-red-700 transform hover:scale-105 transition-all duration-200 flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          </button>
        ) : (
          <div></div>
        )}
        
        <div className="flex gap-3 items-center">
          {(isCreateMode || selectedTown?.status === StatusEnum.ACTIVE) && (
            <button
              type="submit"
              className="px-6 py-3 font-semibold rounded-xl shadow-lg transform transition-all duration-200 flex items-center gap-2 bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-blue-500/30 hover:shadow-xl hover:shadow-blue-500/40 hover:from-blue-600 hover:to-indigo-700 hover:scale-105"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              {isCreateMode ? 'Create Town' : 'Save Changes'}
            </button>
          )}
          <button
            type="button"
            onClick={onCancel}
            className="px-6 py-3 bg-white text-gray-700 font-semibold rounded-xl border-2 border-gray-300 shadow-md hover:shadow-lg hover:bg-gray-50 hover:border-gray-400 transform hover:scale-105 transition-all duration-200 flex items-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
            Cancel
          </button>
        </div>
      </div>
    </form>

    {/* Area Selection Modal */}
    <AreaSearchableSelectionModal
      show={showAreaModal}
      title="Select Area"
      selectedValue={selectedArea?.id || null}
      onSelect={handleAreaSelect}
      onClose={() => setShowAreaModal(false)}
    />
    </>
  );
}
