'use client';

import { AreaDto, StatusEnum, TownDto } from '@data-access/index';
import { useEffect, useState } from 'react';
import AreaSearchableSelectionModal from '../../../search-modals/AreaSearchableSelectionModal';
import SelectionField from '../../customer/components/SelectionField';

interface TownFormProps {
  isCreateMode: boolean;
  selectedTown: TownDto | null;
  successMessage: string | null;
  onSave: (town: TownDto) => void;
  onDelete: () => void;
  onCancel: () => void;
  isAdminUser?: boolean;
}

export default function TownForm({
  isCreateMode,
  selectedTown,
  successMessage,
  onSave,
  onDelete,
  onCancel,
  isAdminUser = false
}: TownFormProps) {
  const [selectedArea, setSelectedArea] = useState<{id: string, name: string} | null>(null);
  const [showAreaModal, setShowAreaModal] = useState(false);
  const [userHasMadeSelections, setUserHasMadeSelections] = useState(false);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  
  // Form state for controlled inputs
  const [formData, setFormData] = useState({
    townName: '',
    changeReason: ''
  });

  // Set initial values when editing (only when user hasn't made selections)
  useEffect(() => {
    if (!isCreateMode && selectedTown && !userHasMadeSelections) {
      if (selectedTown.areaId && selectedTown.areaName) {
        setSelectedArea({
          id: selectedTown.areaId,
          name: selectedTown.areaName
        });
      }
      // Initialize form data
      setFormData({
        townName: selectedTown.townName || '',
        changeReason: selectedTown.changeReason || ''
      });
    }
  }, [isCreateMode, selectedTown, userHasMadeSelections]);
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const townName = formData.townName;
    
    // Validate required fields
    const errors: string[] = [];
    
    if (!selectedArea) {
      errors.push('Please select an area.');
    }
    
    // Validate change reason for non-create mode (only required for non-admin users)
    if (!isCreateMode && !isAdminUser && (!formData.changeReason || formData.changeReason.trim() === '')) {
      errors.push('Please provide a reason for the change.');
    }
    
    if (errors.length > 0) {
      setValidationErrors(errors);
      return;
    }
    
    // Clear validation errors if validation passes
    setValidationErrors([]);
    
    if (isCreateMode) {
      const newTown = {
        townId: '', // Will be generated by the backend
        townName: townName,
        areaId: selectedArea?.id || '',
        areaName: selectedArea?.name || '',
        status: StatusEnum.NEW_RECORD // Default status for new towns
      } as TownDto;
      onSave(newTown);
    } else {
      const updatedTown = {
        ...selectedTown,
        townName: townName,
        areaId: selectedArea?.id || '',
        areaName: selectedArea?.name || '',
        status: StatusEnum.ACTIVE,
        changeReason: formData.changeReason || ''
      } as TownDto;
      onSave(updatedTown);
    }
  };

  const handleAreaSelect = (area: AreaDto) => {
    setSelectedArea({ id: area.areaId, name: area.areaName || '' });
    setUserHasMadeSelections(true);
  };

  const handleClearArea = () => {
    setSelectedArea(null);
  };

  return (
    <>
    <form onSubmit={handleSubmit}>
      {/* Success message */}
      {successMessage && (
        <div className="flex items-center gap-3 rounded-xl border-2 border-green-500 bg-green-50 p-4 text-green-700 shadow-sm">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-green-500 text-sm font-bold text-white">
            ✓
          </div>
          <span className="text-sm font-semibold">{successMessage}</span>
        </div>
      )}

      {/* Validation errors */}
      {validationErrors.length > 0 && (
        <div className="space-y-3 rounded-xl border-2 border-red-500 bg-red-50 p-4 shadow-sm">
          <div className="flex items-center gap-2 text-sm font-semibold text-red-700">
            <span className="text-base">⚠️</span>
            <span>Please fix the following errors:</span>
          </div>
          <ul className="list-disc space-y-1 pl-5 text-sm text-red-700">
            {validationErrors.map((error, index) => (
              <li key={index}>{error}</li>
            ))}
          </ul>
        </div>
      )}
      
      {/* Change Reason Field - First component when displayed */}
      {!isCreateMode && !isAdminUser && (
        <ChangeReasonField
          value={formData.changeReason}
          onChange={(e) => setFormData(prev => ({ ...prev, changeReason: e.target.value }))}
          disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
        />
      )}
      
      {/* Details Container */}
      <div className="space-y-6">
        {/* Basic Information Section */}
        <div className="space-y-4">
          <div className="border-2 border-gray-200 rounded-xl p-4 sm:p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-blue-600 rounded-lg shadow-md">
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
                </svg>
              </div>
              <h3 className="text-base font-bold text-blue-600">
                Town Information
              </h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Town Name */}
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-blue-500 rounded-full"></span>
                  Town Name
                </label>
                <input
                  type="text"
                  name="townName"
                  value={formData.townName}
                  onChange={(e) => setFormData(prev => ({ ...prev, townName: e.target.value }))}
                  placeholder={isCreateMode ? 'Enter town name' : ''}
                  disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
                  className={`w-full px-4 py-3 border-2 rounded-xl text-sm font-medium shadow-sm transition-all duration-200 ${
                    !isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE
                      ? 'border-gray-200 bg-gray-50 text-gray-500 cursor-not-allowed'
                      : 'border-gray-200 bg-white text-gray-700 group-hover:border-blue-300 group-hover:shadow-md'
                  }`}
                  required
                />
              </div>

              {/* Area */}
              <div className="group">
                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full"></span>
                  Area *
                </label>
                <SelectionField
                  label=""
                  selectedItem={selectedArea}
                  onSelect={() => setShowAreaModal(true)}
                  onClear={handleClearArea}
                  buttonText="Select Area"
                  disabled={!isCreateMode && selectedTown?.status !== StatusEnum.ACTIVE}
                />
              </div>
            </div>
          </div>
        </div>

      </div>

      {/* Action Buttons */}
      <div className="mt-8 flex flex-col gap-3 border-t-2 border-gray-200 pt-6 sm:flex-row sm:items-center sm:justify-between">
        {!isCreateMode && selectedTown?.status === StatusEnum.ACTIVE ? (
          <button
            type="button"
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              onDelete();
            }}
            className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-6 py-3 font-semibold text-white shadow-sm transition-colors duration-200 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          </button>
        ) : (
          <div className="hidden sm:block" />
        )}

        <div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row sm:items-center">
          {(isCreateMode || selectedTown?.status === StatusEnum.ACTIVE) && (
            <button
              type="submit"
              className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white shadow-sm transition-colors duration-200 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              {isCreateMode ? 'Create Town' : 'Save Changes'}
            </button>
          )}
          <button
            type="button"
            onClick={onCancel}
            className="flex items-center justify-center gap-2 rounded-xl border-2 border-gray-300 bg-white px-6 py-3 font-semibold text-gray-700 shadow-sm transition-all duration-200 hover:border-gray-400 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
            Cancel
          </button>
        </div>
      </div>
    </form>

    {/* Area Selection Modal */}
    <AreaSearchableSelectionModal
      show={showAreaModal}
      title="Select Area"
      selectedValue={selectedArea?.id || null}
      onSelect={handleAreaSelect}
      onClose={() => setShowAreaModal(false)}
    />
    </>
  );
}
